common: &SHARED
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: password
  
development:
  <<: *SHARED
  database: wildcountrytech_development

test:
  <<: *SHARED
  database: wildcountrytech_test

staging:
  <<: *SHARED
  database: wildcountrytech_staging
    
production:
  <<: *SHARED
  database: wildcountrytech_production
